node=A
modulation=QAM64
#   ------   levels   ------ 
#(trace/debug/info/warn/error/critical)
log-level=info
# log-dsp=info
# log-sdr=info
# log-tun=info
# log-gui=info
# log-main=info
# log-socket=info
